config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :keywords do
    member do
      get :search_day_count, :weibo, :new_search, :reposts, :baidu_news, :ctn_search, :re_search
    end
  end

  resources :kibers

  resources :captchas

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'visitors#index'
end

app/models/captcha.rb
class Captcha
  include Mongoid::Document
  
  field :created_at,     :type => Integer, :default => Time.now.to_i
  field :code,           :type => String
  field :status,         :type => Integer, :default => 0
end

app/controllers/captchas_controller.rb
class CaptchasController < ApplicationController
  before_action :set_captcha, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => :create  
  
   # you can disable csrf protection on controller-by-controller basis:  
   skip_before_filter :verify_authenticity_token
  # GET /captchas
  # GET /captchas.json
  def index
    # binding.pry
    @captchas = Captcha.where(:is_correct => nil)
  end

  # GET /captchas/1
  # GET /captchas/1.json
  def show
  end

  # GET /captchas/new
  def new
    @captcha = Captcha.new
  end

  # GET /captchas/1/edit
  def edit
  end

  # POST /captchas.json
  def create
    @captcha = Captcha.where(:id => params[:captcha][:id]).first
    respond_to do |format|
      if @captcha && @captcha.update(captcha_params)
        if [4,5].include @captcha.code.length
          format.json { render :json => {:result => true} }
        else
          format.json { render :json => {:result => false} }
        end
        while true
          sleep(1)
          @captcha.reload
          case @captcha.status
          when 2
            format.json { render :json => {:result => true} }
            break
          when 3
            format.json { render :json => {:result => false} }
            break
          else
            sleep(4)
            next
          end
          @captcha.destroy
        end
      else
        format.json { render :json => {:result => false} }
      end
    end
  end

  # PATCH/PUT /captchas/1
  # PATCH/PUT /captchas/1.json
  def update
    respond_to do |format|
      if @captcha.update(captcha_params)
        format.html { redirect_to captchas_path, notice: '验证码填写成功.' }
      else
        format.html { redirect_to captchas_path, notice: '验证码填写失败.' }
      end
    end
  end

  # DELETE /captchas/1
  # DELETE /captchas/1.json
  def destroy
    @captcha.destroy
    respond_to do |format|
      format.html { redirect_to captchas_url, notice: 'Captcha was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_captcha
      @captcha = Captcha.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def captcha_params
      params.require(:captcha).permit(:code)
    end
end

app/helpers/captchas_helper.rb
module CaptchasHelper
end

app/views/captchas/_form.html.erb
<%= form_for(@captcha) do |f| %>
  <% if @captcha.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@captcha.errors.count, "error") %> prohibited this captcha from being saved:</h2>

      <ul>
      <% @captcha.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/captchas/edit.html.erb
<h1>Editing captcha</h1>

<%= render 'form' %>

<%= link_to 'Show', @captcha %> |
<%= link_to 'Back', captchas_path %>

app/views/captchas/index.html.erb
<!-- content for head -->
<% content_for :header do %>
  <meta http-equiv="refresh" content="12">
<% end %>

<h1>待输入验证码列表</h1>
    <div class="row">
    <% @captchas.each do |captcha| %>
      <div class="col-sm-6 col-md-2">
        <%= form_for captcha do |f| %>
          <fieldset>
            <div class="form-group">
              <img src="/captchas/<%= captcha.id %>.png">
            </div>
            <div class="form-group">
              <label for="disabledTextInput">请输入验证码:</label>
              <%= f.text_field :code, :class => "form-control" %>
            </div>
            <%= link_to '删除', captcha, method: :delete, data: { confirm: '确定删除吗?' }, :class => "btn btn-default" %>
            <%= f.submit "确定", :class => "btn btn-primary" %>
          </fieldset>
        <% end %>
      </div>
    <% end %>
    </div>
<br>

app/views/captchas/new.html.erb
<h1>New captcha</h1>

<%= render 'form' %>

<%= link_to 'Back', captchas_path %>

app/views/captchas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_captcha_path(@captcha) %> |
<%= link_to 'Back', captchas_path %>