config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :keywords do
    member do
      get :search_day_count, :weibo, :new_search, :reposts, :baidu_news, :ctn_search, :re_search
    end
  end

  resources :kibers

  resources :captchas

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'visitors#index'
end

app/models/kiber.rb
class Kiber
  include Mongoid::Document
  include Mongoid::Timestamps
  field :starttime        , :type => Integer
  field :crdtime          , :type => Integer
  field :gap              , :type => Integer
  field :endtime          , :type => Integer
  field :page             , :type => Integer, :default => 1
  field :xsort            , :type => Boolean, :default => false
  field :ori              , :type => Boolean, :default => true
  field :all_count        , :type => Integer, :default => 0
  field :now_count        , :type => Integer, :default => 0
  field :status           , :type => Integer, :default => 0
  field :mark             , :type => String
  field :is_active        , :type => Boolean, :default => false
  field :kid              , :type => String

  belongs_to :keyword
end

app/controllers/kibers_controller.rb
class KibersController < ApplicationController
  before_action :set_kiber, only: [:show, :edit, :update, :destroy]

  # GET /kibers
  # GET /kibers.json
  def index
    @nc = WeiboUser.need_crawl.count
  end

  # GET /kibers/1
  # GET /kibers/1.json
  def show
  end

  # GET /kibers/new
  def new
    @kiber = Kiber.new
  end

  # GET /kibers/1/edit
  def edit
  end

  # POST /kibers
  # POST /kibers.json
  def create
    @kiber = Kiber.new(kiber_params)

    respond_to do |format|
      if @kiber.save
        format.html { redirect_to @kiber, notice: 'Kiber was successfully created.' }
        format.json { render :show, status: :created, location: @kiber }
      else
        format.html { render :new }
        format.json { render json: @kiber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kibers/1
  # PATCH/PUT /kibers/1.json
  def update
    respond_to do |format|
      if @kiber.update(kiber_params)
        format.html { redirect_to @kiber, notice: 'Kiber was successfully updated.' }
        format.json { render :show, status: :ok, location: @kiber }
      else
        format.html { render :edit }
        format.json { render json: @kiber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kibers/1
  # DELETE /kibers/1.json
  def destroy
    @kiber.destroy
    respond_to do |format|
      format.html { redirect_to kibers_url, notice: 'Kiber was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kiber
      @kiber = Kiber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kiber_params
      params[:kiber]
    end
end

app/helpers/kibers_helper.rb
module KibersHelper
end

app/views/kibers/_form.html.erb
<%= form_for(@kiber) do |f| %>
  <% if @kiber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kiber.errors.count, "error") %> prohibited this kiber from being saved:</h2>

      <ul>
      <% @kiber.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kibers/edit.html.erb
<h1>Editing kiber</h1>

<%= render 'form' %>

<%= link_to 'Show', @kiber %> |
<%= link_to 'Back', kibers_path %>

app/views/kibers/index.html.erb
  <div class="panel-body">
    共有 <%= @nc %> 个微博用户需要爬取, <%= link_to("现在爬取", "url" ) %>
  </div>

app/views/kibers/new.html.erb
<h1>New kiber</h1>

<%= render 'form' %>

<%= link_to 'Back', kibers_path %>

app/views/kibers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kiber_path(@kiber) %> |
<%= link_to 'Back', kibers_path %>