config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :keywords do
    member do
      get :search_day_count, :weibo, :new_search, :reposts, :baidu_news, :ctn_search, :re_search
    end
  end

  resources :kibers

  resources :captchas

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'visitors#index'
end

app/models/keyword.rb
require 'csv'

class Keyword
  include Mongoid::Document
  field :content          , :type => String
  field :s_content        , :type => String
  field :starttime        , :type => Integer, :default => (Time.now.at_beginning_of_day - 360.days).to_i
  field :crdtime          , :type => Integer, :default => (Time.now.at_beginning_of_day - 360.days).to_i
  field :endtime          , :type => Integer, :default => (Time.now.at_beginning_of_day - 1.days).to_i
  field :day_count        , :type => Hash,    :default => {}
  field :ori_day_count    , :type => Hash,    :default => {}
  field :news_day_count   , :type => Hash,    :default => {}
  field :is_deleted       , :type => Boolean, :default => false
  field :tags             , :type => Array,   :default => []

  has_many :kibers
  has_and_belongs_to_many :weibos
  has_and_belongs_to_many :weibo_users
  has_many :baidu_news

  scope :active, -> { where :is_deleted => false}

  def get_kiber(st, ac)
    kibers.where(:kid => "#{st}-#{ac}").first
  end

  def all_to_csv
    baidu_news_to_csv
    day_count_to_csv
    weibo_to_csv
    repost_to_csv
  end

  def w_to_csv

    CSV.open("tmp/csv/#{content}-微博-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb") do |csv|
      csv << ["用户名", "内容", "发表时间", "月", "天", "小时","转载数", "个人认证", "商业认证", "感情色彩"].map do |str| 
        str.encode('gbk', 'utf-8',{:invalid => :replace, :undef => :replace, :replace => '?'})
      end
      weibos.each do |w|
        tt = Time.at(w.created_at)
        csv << [w.user_name, w.content, tt, tt.month, tt.day, tt.hour, w.reposts_count, b2i(w.approve), b2i(w.approve_co)].map do |str|
          str.to_s.encode('gbk','utf-8',{:invalid => :replace, :undef => :replace, :replace => '?'})
        end
      end      
    end
  end

  def b2i(b)
    b ? 1 : 0
  end

  def w2_to_csv
    CSV.open("tmp/csv/#{content}-微博-cctv6.csv", "wb") do |csv|
      csv << ["用户名", "内容", "发表时间", "转载数", "评论数", "点赞数"]
      reposts_count = comments_count = ups_count = 0
      reposts_count_2 = comments_count_2 = ups_count_2 =0
      weibos.each do |w|
        tt = Time.at(w.created_at)
        csv << [w.user_name, w.content, tt.strftime("%F %T") , w.reposts_count, w.comments_count, w.ups_count]
        reposts_count += w.reposts_count
        comments_count += w.comments_count
        ups_count += w.ups_count
        reposts_count_2 += w.reposts_count * w.reposts_count
        comments_count_2 += w.comments_count * w.comments_count
        ups_count_2 += w.ups_count * w.ups_count
      end
        csv << ["关键词", "帖子总量", "总转载数", "总评论数" , "总点赞数", "结果"]
        csv << [content, weibos.count, reposts_count , comments_count, ups_count, 
          Math.log10(weibos.count) * (Math.sqrt(reposts_count_2/weibos.count) + Math.sqrt(comments_count_2/weibos.count) + Math.sqrt(ups_count_2/weibos.count)) / 3.0]
    end
  end


  def self.w3_to_csv
    CSV.open("tmp/csv/微博-cctv6结果.csv", "wb") do |csv|
      csv << ["关键词", "帖子总量", "总转载数", "总评论数" , "总点赞数", "ln count", "转载", "评论", "点赞", "结果"]
      Keyword.where(:is_deleted => false).each do |k|
        weibos = k.weibos
        reposts_count = comments_count = ups_count = 0
        reposts_count_2 = comments_count_2 = ups_count_2 =0
        weibos.each do |w|
          tt = Time.at(w.created_at)
          reposts_count += w.reposts_count
          comments_count += w.comments_count
          ups_count += w.ups_count
          reposts_count_2 += w.reposts_count * w.reposts_count
          comments_count_2 += w.comments_count * w.comments_count
          ups_count_2 += w.ups_count * w.ups_count
        end
          csv << [k.content, weibos.count, reposts_count , comments_count, ups_count,
            Math.log10(weibos.count), Math.sqrt(reposts_count_2/weibos.count), Math.sqrt(comments_count_2/weibos.count), Math.sqrt(ups_count_2/weibos.count),
            Math.log10(weibos.count) * (Math.sqrt(reposts_count_2/weibos.count) + Math.sqrt(comments_count_2/weibos.count) + Math.sqrt(ups_count_2/weibos.count)) / 3.0]
      end
    end
  end


  def baidu_news_to_csv
    CSV.open("tmp/csv/#{content}-百度新闻-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb") do |csv|
    # CSV.open("tmp/csv/#{content}-百度新闻-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb") do |csv|
      csv << ["标题", "摘要","地址", "来源", "日期", "相同新闻数量(百度估算)","相同新闻来源"]
      baidu_news.each do |bn|
        csv << [
          bn.title.encode("GBK", invalid: :replace, undef: :replace, replace: "?"),
          bn.summary.encode("GBK", invalid: :replace, undef: :replace, replace: "?"),
          bn.url,
          bn.source.encode("GBK", invalid: :replace, undef: :replace, replace: "?"), 
          Time.at(bn.created_at), 
          (bn.lcountents.count rescue 0) , 
          (bn.lcountents.map { |e| "#{e["source"]}(#{e["created_at"]})".encode("GBK", invalid: :replace, undef: :replace, replace: "?") }.join(' ') rescue '')]
      end
    end
  end

  def day_count_to_csv
    CSV.open("tmp/csv/#{content}-微博每日提及数-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb", encoding: "GBK") do |csv|
      csv << ["日期", "提及数"]
      day_count.each do |dd, dc|
        csv << [dd, dc]
      end
    end
  end

  def weibo_to_csv
    CSV.open("tmp/csv/#{content}-微博列表-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb") do |csv|
      csv << ["用户名", "内容", "发表时间", "转载数", "博主粉丝数", "博主关注数", "关注品牌媒体"]
      weibos.each do |w|
        csv << [w.user_name, w.content, Time.at(w.created_at), w.reposts_count,w.weibo_user.fans_count, w.weibo_user.follow_count, 
          w.weibo_user.follows.all.select{|wu| wu.verified_type == 1}.map(&:name).join(' ')]
      end
    end
  end

  def repost_to_csv(mid = nil)
    CSV.open("tmp/csv/#{content}-微博转发路径-#{Time.at(starttime).strftime('%F')}-#{Time.at(endtime).strftime('%F')}.csv", "wb") do |csv|
      _ws = mid.blank? ? weibos.hot : [Weibo.find_by(:mid => mid)]
      _ws.each do |w|
        csv << [w.user_name, w.content, Time.at(w.created_at), w.reposts_count]
          w.reposts.each do |ww|
          csv << ['',ww.user_name, ww.content, Time.at(ww.created_at), ww.reposts_count]
          ww.reposts.each do |www|
            csv << ['', '',www.user_name, www.content, Time.at(www.created_at), www.reposts_count]
            www.reposts.each do |wwww|
              csv << ['','','',wwww.user_name, wwww.content, Time.at(wwww.created_at), wwww.reposts_count]
              wwww.reposts.each do |wwwww|
                csv << ['','','','',wwwww.user_name, wwwww.content, Time.at(wwwww.created_at), wwwww.reposts_count]
                wwwww.reposts.each do |wwwwww|
                  csv << ['','','','','',wwwwww.user_name, wwwwww.content, Time.at(wwwwww.created_at), wwwwww.reposts_count]
                  wwwwww.reposts.each do |wwwwwww|
                    csv << ['','','','','',wwwwwww.user_name, wwwwwww.content, Time.at(wwwwwww.created_at), wwwwwww.reposts_count]
                    wwwwwww.reposts.each do |wwwwwwww|
                      csv << ['','','','','',wwwwwwww.user_name, wwwwwwww.content, Time.at(wwwwwwww.created_at), wwwwwwww.reposts_count]
                      wwwwwwww.reposts.each do |wwwwwwwww|
                        csv << ['','','','','',wwwwwwwww.user_name, wwwwwwwww.content, Time.at(wwwwwwwww.created_at), wwwwwwwww.reposts_count]
                        wwwwwwwww.reposts.each do |wwwwwwwwww|
                          csv << ['','','','','',wwwwwwwwww.user_name, wwwwwwwwww.content, Time.at(wwwwwwwwww.created_at), wwwwwwwwww.reposts_count]
                        end
                      end
                    end
                  end
                end
              end
            end
          end
        end
      end
    end
  end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: [:show, :edit, :update, :destroy, :search_day_count, :new_search, :weibo, :ctn_search, :re_search]

  # GET /keywords
  # GET /keywords.json
  def index
    if params[:all]
      @keywords = Keyword.all
    else
      @keywords = Keyword.where(:is_deleted => false)
    end
  end

  # GET /keywords/1
  # GET /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  def baidu_news
    
  end

  def wpath
    
  end

  def weibo
    @weibos = @keyword.weibos.hot
  end

  def repost
    Reposts.perform_async params[:mid]
    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: '开始爬取!' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /keywords/1/edit
  def edit

  end

  def new_search
    kid = "#{params[:starttime]}-#{params[:all_count]}"
    params[:starttime] = Time.parse(params[:starttime]).to_i
    # if all_count < 1000 
    k = @keyword.kibers.create(
      starttime: params[:starttime],
      crdtime: params[:starttime],
      endtime: params[:starttime] + 73.days,
      all_count: params[:all_count],
      kid: kid,
      gap: 24
    )
    # binding.pry
    @keyword.save
    # WeiboSearchWorker.perform_async k.id.to_s
    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: '开始爬取!' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  def ctn_search
    k = Kiber.find(params[:kid])
    WeiboSearchWorker.perform_async k.id.to_s
    respond_to do |format|
      format.html { redirect_to @keyword, notice: '继续爬取!' }
      format.json { render :show, status: :created, location: @keyword }
    end
  end

  def re_search
    k = Kiber.find(params[:kid])
    k.update(page:1, crdtime: k.starttime)
    WeiboSearchWorker.perform_async k.id.to_s
    respond_to do |format|
      format.html { redirect_to @keyword, notice: '继续爬取!' }
      format.json { render :show, status: :created, location: @keyword }
    end
    
  end

  def search_day_count
    DayCountWorker.perform_async @keyword.id.to_s
    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: '开始爬取!' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /keywords
  # POST /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to @keyword, notice: 'Keyword was successfully created.' }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1
  # PATCH/PUT /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to @keyword, notice: 'Keyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1
  # DELETE /keywords/1.json
  def destroy
    @keyword.destroy
    respond_to do |format|
      format.html { redirect_to keywords_url, notice: 'Keyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_keyword
    @keyword = Keyword.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def keyword_params
    permited_params = params.require(:keyword).permit(:content, :s_content, :starttime, :endtime, :day_count)
    permited_params["starttime"] = Time.parse(permited_params["starttime"]).to_i
    permited_params["crdtime"]   = permited_params["starttime"]
    permited_params["endtime"]   = Time.parse(permited_params["endtime"]).to_i
    permited_params
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
  def st(_t)
    Time.at(_t).strftime("%F")
  end

  def can_count(real_count)
    real_count > 24000 ? 24000 : real_count
  end

  
end

app/views/keywords/_form.html.erb
<%= form_for(@keyword) do |f| %>
  <% if @keyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
      <% @keyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :s_content %><br>
    <%= f.text_field :s_content %>
  </div>
  <div class="field">
    <%= f.label :starttime %><br>
    <%= f.date_field :starttime, value: st(@keyword.starttime) %>
  </div>
  <div class="field">
    <%= f.label :endtime %><br>
    <%= f.date_field :endtime, value: st(@keyword.endtime) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/keywords/edit.html.erb
<h1>Editing keyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @keyword %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/index.html.erb
<h1>关键词列表</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>关键词</th>
      <th>开始时间</th>
      <th>结束时间</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.content %>(<%= keyword.weibos.count %>)</td>
        <td><%= st(keyword.starttime) %></td>
        <td><%= st(keyword.endtime) %></td>
        <td><%= link_to '微博搜索结果', keyword %></td>
        <td><%= link_to '热门微博(传播路径)', action: :weibo, id: keyword %></td>
        <td><%= link_to '百度新闻', action: :weibo, id: keyword %></td>
        <td><%= link_to '品牌媒体关注', action: :weibo, id: keyword %></td>
        <td><%= link_to '删除', keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Keyword', new_keyword_path %>

app/views/keywords/new.html.erb
<h1>New keyword</h1>

<%= render 'form' %>

<%= link_to 'Back', keywords_path %>

app/views/keywords/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>关键字:</strong>
  <%= @keyword.content %>
</p>

<p>
  <strong>从:</strong>
  <%= st(@keyword.starttime) %>
  <strong>到:</strong>
  <%= st(@keyword.endtime) %>
  <%= link_to("开始抓取", controller: "keywords", action: "search_day_count", id: @keyword) %>
</p>

<table class="table table-hover">
  <thead>
    <tr>
      <th>日期</th>
      <th>微博数量</th>
      <th>已抓取数量</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @keyword.day_count.each do |k, v| %>
      <tr>
        <td><%= k %></td>
        <td><%= v %></td>
        <% if kb = @keyword.get_kiber(k, v) %>
        <td><%= kb.now_count %>  
          <%= link_to("继续抓取", controller: "keywords", action: "ctn_search", :kid => kb.id )%>
          <%= link_to("重新抓取", controller: "keywords", action: "re_search", :kid => kb.id )%>
           </td>
        <% else %>
        <td> <%= link_to("开始抓取", controller: "keywords", action: "new_search", :starttime => k, :all_count => v )%> </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_keyword_path(@keyword) %> |
<%= link_to 'Back', keywords_path %>

app/views/keywords/weibo.html.erb
<h1>热门微博</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>发帖人</th>
      <th width="40%">内容</th>
      <th>转发次数</th>
      <th>传播路径</th>
    </tr>
  </thead>

  <tbody>
    <% @weibos.each do |weibo| %>
      <tr>
        <td><%= link_to(weibo.weibo_user.name, weibo.weibo_user.get_url) %> </td>
        <td><%= weibo.content  %></td>
        <td><%= link_to(weibo.reposts_count, "http://weibo.com#{weibo.reposts_url}")  %></td>
        <td> <%= link_to("点击采集传播路径", controller: "keywords", action: "reposts", :mid => weibo.mid)%> </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>