config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  resources :keywords do
    member do
      get :search_day_count, :weibo, :new_search, :reposts, :baidu_news, :ctn_search, :re_search
    end
  end

  resources :kibers

  resources :captchas

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  root to: 'visitors#index'
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to '状态', "/keywords" %></li>
<li><%= link_to '验证码', "/captchas" %></li>
<li><%= link_to '账号', "/admin/account" %></li>
<li><%= link_to '代理', "/admin/proxy" %></li>
<li><%= link_to 'sidekiq', sidekiq_web_path %></li>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Shall Wei" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Shall Wei" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield :header %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <div class="panel panel-default">
        <div class="panel-body">
          当前可用账号数量为 <%= @status[:ac] %> 个, 其中 <%= @status[:acc] %> 正在使用, 可用代理数量为 <%= @status[:pc] %> 个.
        </div>
      </div>

       <%= yield %>
    </main>
  </body>
</html>